name: ${project.name}
main: nu.nerd.checkpoint.CheckpointPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
softdepend: [Multiverse-Core]
authors: [Dumbo52]
commands:
  checkpoint:
    description: Manage checkpoints
    permission: checkpoint.admin
  course:
    description: Manage checkpoint courses
    permission: checkpoint.admin
  trigger:
    description: Manage checkpoint triggers
    permission: checkpoint.admin
permissions:
  checkpoint.admin:
    description: Allows players to to modify checkpoint courses and checkpoints
    default: op
  checkpoint.use:
    description: Allows players to set and teleport back to checkpoints
    default: true
